### PR TITLE
Design updates to the respond-to-an-application flow

### PR DESCRIPTION
**Pull request by duncanjbrown**
## Context

There are some inconsistencies in the design around the "respond to application" flow for providers.

## Changes proposed in this pull request

One by one, from the card:

- Move the candidate name above the title on Confirm Rejection form consistent with placing on other forms.

✅ Done

### Before

Screenshot 2020-03-30 at 16 50 15

### After

Screenshot 2020-03-30 at 16 50 05

This introduces a bit of duplication but the UI benefit from consistency is worth it

- Vertical space between 'Continue' button and cancel link (all change/reject forms) should be reduced

💪 Fixed upstream in the formbuilder and will be picked up once the release makes it to rubygems
https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases/tag/v1.1.7

- Respond to application error message should appear above radio group and below H1
https://ukgovernmentdfe.slack.com/files/UPWN7EC2V/F010VTG33NK/image.png

😑 Imperfectly done with a hack — see commit. Probably needs an upstream change in the form builder to be 📐.

### Before

Screenshot 2020-03-30 at 16 55 37

### After

Screenshot 2020-03-30 at 16 54 35

- "Tell the candidate why their application was rejected" on Reject Application form should be a label.
https://ukgovernmentdfe.slack.com/files/UPWN7EC2V/F010J3KU0Q1/image.png

✅  It's already a label

- 'Change' link should be present against conditions in confirmation step: /provider/applications/<id>/offer/confirm

❌ Not done. This is tricky as we don't have an intermediate step where we store the conditions. They do exist in memory at this point but we'd have to fake a POST to get them back into the form for editing. When we come to create individual conditions we might solve this for free, so I think we should punt it for now?

## Link to Trello card

https://trello.com/c/2B8lduBk/1822-design-updates-to-respond-change-reject-application

## Things to check

- [X] This code doesn't rely on migrations in the same Pull Request
- [X] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [X] API release notes have been updated if necessary
- [X] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by adamsilver** [comment]
image

This screen should be:

```
Caption: {{Candidate name}}
H1: Tell the candidate why you're rejecting their application
Hint: We'll send them your feedback
[textarea]

[Continue]
```

**Comment by adamsilver** [comment]
image

The button should read ‘Reject application’

Above the button should be this:

image

The summary list should have one row—just the reasons the provider typed on the previous page with a change link back to that page.

**Comment by duncanjbrown** [comment]
I've answered the comments I hope, screenshots below.

Introducing a back link for editing rejection reasons is a bit beyond scope here I think, but let's put a ticket in the backlog if it's important

### Giving reasons for rejection

Screenshot 2020-04-01 at 13 22 53

Screenshot 2020-04-01 at 13 22 58

### Confirming rejection

Screenshot 2020-04-01 at 13 37 46

**Comment by duncanjbrown** [comment]
@adamsilver this should (finally!) be ready now. The label is now an `h1`, but I wasn't able to get the caption (the candidate's name) in too. This is due to the form builder. If you think captions-in-labels is enough of a thing to merit support from the form builder, I can try and get it added.

Current state:

Screenshot 2020-04-08 at 12 18 37

**Comment by adamsilver** [comment]
@duncanjbrown 

I think you can merge as is.

> If you think captions-in-labels is enough of a thing to merit support from the form builder, I can try and get it added.

yes please

**Pull request merged**
