### PR TITLE
[DNM] 1665 soft delete support users

### PR DESCRIPTION
**Pull request by steventux**
## Context

Depends on https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training/pull/1504

We've recently added the ability to delete support users, but we need to retain the records for the audit history to work correctly so soft deletion is the better option.

## Changes proposed in this pull request

- Adds the `paranoia` gem
- Applies soft deletion to `SupportUser` model

## Link to Trello card

https://trello.com/c/AYxmAxXj/1665-offboarding-from-support

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
This looks great, but I notice the author of `paranoia` has deprecated his own gem! Should we consider `discard` instead? https://github.com/rubysherpas/paranoia/blob/core/README.md  https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid

**Comment by duncanjbrown** [comment]
Looking good! Comment above and inline

**Comment by steventux** [comment]
Closing for now to find an alternative to using `paranoia` gem

**Comment by tvararu** [comment]
_adds `paranoia` to his list of weirdly named ruby libraries_

**Pull request closed without merging**
