### PR TITLE
83 - Add Google Tag Manager to the app

### PR DESCRIPTION
**Pull request by tvararu**
### Context

This will allow us to track and improve the service.

### Link to Trello card

[83 - Add Google Analytics to the app](https://trello.com/c/Jvwh3BvK)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
A couple of questions:

- do we want Google Tag Manager? If so, could we install that instead of raw ga, and configure events etc in there? I like GTM.
- what do we want behaviour to be in non-prod environments? at the moment this will log pageviews in development

**Comment by tvararu** [comment]
@duncanjbrown:

- We use GA on Publish and Find with exactly this setup I think, not tag manager though Google did give me copy/pastable code for Tag Manager. The BAs don't have a preference, but if we do then happy to change to that
- We use a view called "Internal Traffic Filtered", see below, which is configured to only show us traffic from the live environment (currently s106d01, but will be changed); we use this setup in the other apps too, has been okay so far


Screenshot 2019-09-30 at 10 28 58

**Comment by tvararu** [comment]
@duncanjbrown I'm happy to change this to GTM 👍

**Comment by tvararu** [comment]
@duncanjbrown updated!

**Pull request merged**
