### PR TITLE
Providers can change offers to rejections

### PR DESCRIPTION
**Pull request by duncanjbrown**
## Draft for now

Needs a look from designers. There’s an argument that the radio buttons are unnecessary and these alternatives could be links instead

## Context

Providers need to be able to reject applications that already have offers.

## Changes proposed in this pull request

Create a new `ChangeDecision` controller in the Provider Interface. Its job is to present users with a set of radio buttons and redirect them to the right place once they pick one.

Screenshot 2020-01-16 at 17 27 40

Screenshot 2020-01-16 at 17 12 02

The copy is mine 😬 

## Link to Trello card

https://trello.com/c/KLy8enLu/1482-ui-reject-offered-applications

## Things to check

- [X] This code doesn't rely on migrations in the same Pull Request
- [X] API release notes have been updated if necessary
- [X] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
In the cold light of morning, I think I overdid this. The component is not very nice - a plain old view would probably be better?

**Comment by tvararu** [comment]
@duncanjbrown the two main reasons I would advocate for a component:

- It's being used in a number of different places
- It has many different states which all need to be tested (unit tests are simpler than system tests for this)

We're not taking advantage of either here, so a plain view would suffice yes :)

**Comment by fofr** [comment]
A single option Radio is a little odd. Content works well though.

**Comment by adamsilver** [comment]
## Screen 1
I had the button text initially as ‘Change offer’ but having seen your ‘Change decision’ I think given the button in the initial state says ‘Respond to application’ I would suggest this becomes ‘Change response’.

If we prefer ‘Change decision’ then I think we should change ‘Respond to application’ to ‘Make decision’.

## Screen 2
The h1 should match the button text if we change it (see above)

The h1 should be inside the legend (if it isn't already) and the gap should be a lot smaller between the legend and the hint

Change the hint text to ‘You've made this candidate an offer, but they've not accepted it yet.’

I'm not sure about the radio button's label and hint. It's not quite a reject but rescind isn't all that clear.

## Single radio button

I gather this will be feature flagged, @fofr, so won't go out until we have the flows for the other radio buttons.

**Comment by laurahermionetennant92** [comment]
Hi folks,
I have made some content updates on the is branch. 
Content now works for this single option. When we add other radio button options it will need to be looked at again.

**Comment by laurahermionetennant92** [comment]
Screenshot 2020-01-17 at 14 44 41
At this point, as a provider I have gone through the flow of changing my decision from offer to rejection.
But we want to enable a rejection to go back to an offer if need be – at any time, right?
Because this is different from an offer accepted by a candidate and therefore binding.
This is a rejection which may have been noted by the candidate but is not in any way ‘binding’ (and also potentially the candidate would be thrilled to have it go from rejected to offer)

**Comment by laurahermionetennant92** [comment]
So at this point, we should have a Change decision button on this page… which appears if you’ve rejected, but not if you’ve offered and been accepted
Screenshot 2020-01-17 at 15 11 22

**Comment by laurahermionetennant92** [comment]
And on this page
Screenshot 2020-01-17 at 15 07 45
, we should have a Change decision button on this page… which appears if you’ve rejected, but not if you’ve offered and been accepted

**Comment by laurahermionetennant92** [comment]
At
Screenshot 2020-01-17 at 14 52 45
 this point, we should have a Change decision button on this page… which appears if you’ve rejected, but not if you’ve offered and been accepted

**Comment by laurahermionetennant92** [comment]
Also note to @adamsilver  that we need to look at how the candidate's deets are displayed and keep them consistent all through the work flow – maybe stacked (name, course, provider?)
Screenshot 2020-01-17 at 15 31 47

**Comment by laurahermionetennant92** [comment]
@adamsilver I see what you mean re decision versus response – for some reason can't find this instance to change, can you fix?
Screenshot 2020-01-17 at 15 52 22

**Comment by duncanjbrown** [comment]
Closing this PR pending movement on https://trello.com/c/vdo2FhAz/1487-design-change-state-from-offered-to-rejected

**Pull request closed without merging**
