### PR TITLE
Upgrade to 0.7.10 of govuk_design_system_formbuilder

### PR DESCRIPTION
**Pull request by RobertM905**
### Context

We are currently using the `govuk_design_system_formbuilder` version `0.7.9` which is behind the current `0.7.10` version available which adds new features including a way to show the form error summary. We are currently hand rolling the error summary functionality using custom partials and helpers.

### Changes proposed in this pull request

The `Gemfile` has been updated to include the most recent version of the `govuk_design_system_formbuilder` gem `0.7.10`.

The form views for `contact_details`, `personal_details` and `degrees` have been updated to make use of the new `f.govuk_error_summary` function to display the error summary.

The spec files `candidate_entering_contact_details_spec.rb`, `candidate_entering_personal_details_spec.rb` and `candidate_entering_degree_spec.rb` have been updated to use the new form input field identifier when test for linking between the error summary and the form fields. 

### Guidance to review

Test the error summary functionality when linking to form fields. (Check our custom validation)
Run tests to check form field identifiers are correct in tests.

### Link to Trello card

[673 - Upgrade to 0710 of govuk_design_system_formbuilder](https://trello.com/c/Vref7AQE/673-upgrade-to-0710-of-govukdesignsystemformbuilder)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
Starting a review...

**Comment by duncanjbrown** [comment]
Rebased — fixing erb-lint errors...

**Comment by duncanjbrown** [comment]
:+1: The code looks very good to me.

I think we could handle multiple validation errors better — see the last entry in this list.

Screenshot 2019-08-05 at 15 55 18

And next to the field:

Screenshot 2019-08-05 at 15 54 30

Ought we to show more than one error per field?

**Comment by RobertM905** [comment]
I have added `allow_blank: true` to the degree model validation. To reduce the amount off error messages shown for a single form field. 

Screenshot 2019-08-05 at 17 20 12
 
Screenshot 2019-08-05 at 17 23 25

**Comment by kjdchapman** [comment]
I'm worried `allow_blank` will confuse a future user.

Should we try and address this upstream? From Slack, talking about the [formbuilder gem](https://github.com/DFE-Digital/govuk_design_system_formbuilder/):
> (general agreement that showing one error is the best UX)

@peteryates:
> I like the sound of that, and I agree that making that decision falls outside the responsibility of the gem. I'm leaning towards just showing the first error; if the validation was structured so that they are applied in order of importance (I assume Rails adds the errors in the order they are defined), would that be sufficient?

**Comment by alexdesi** [comment]
I agree with @kjdchapman, `allow_blank: true` is misleading, and actually, that the field `year` is not allowed to be empty!

**Comment by RobertM905** [comment]
Duncan and myself worked on a potential fix in the gem which is in a Draft PR here: 
[Formbuilder Gem Draft PR](https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/20). 

Would like to have a dialogue about this with there so please check it out :)

**Comment by RobertM905** [comment]
@peteryates who maintains the formbuilder gem that we use is happy the changes suggested and has merged the PR [Here](https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/20). 

These changes will now be included in the next release of the gem along with some upgrades to support `version 3` of the `govuk-design-system`.

**Comment by kjdchapman** [comment]
Should we close this whilst we wait for the next version of the formbuilder gem? Or merge it in its current state? I have a weak preference for the former.

**Comment by duncanjbrown** [comment]
I think we agreed to close it for now but keep the branch around

**Pull request closed without merging**
