### PR TITLE
Add Pull Request template

### PR DESCRIPTION
**Pull request by duncanjbrown**
### Context

Following conversation in [Confluence](https://dfedigital.atlassian.net/wiki/spaces/BaT/pages/1117257789/Dev+playbook), we would like a PR template.

Jake suggested we look at Find's template. I took that and cut off the checklist — it felt a bit prescriptive, and we can grow our own

### Changes proposed in this pull request

Add `PULL_REQUEST_TEMPLATE.md` with boilerplate for new PRs

### Guidance to review

Review the language. Check the implementation follows the [official GitHub guidance](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
- Added a link to Trello section
- Added a note about screenshots to the main "Changes proposed" section. We agreed IRL on having a single template rather than two, on the grounds that people might forget the UI one exists

**Comment by duncanjbrown** [comment]
> I like this! I think it'd be good to have a little more explaining/examples for the sections - was that the checklist you talked about dropping off?

That was literally a checklist: https://github.com/DFE-Digital/manage-courses-backend/blob/master/.github/PULL_REQUEST_TEMPLATE.md. I feel like we'll discover the things we forget in due course, then we can make our own list? Don't want us to nanny ourselves unnecessarily.

> 
> Either way, improvement on where we are now - feel free to merge, or I can give examples of explanatory text?

If you had a bit of text to add that would be great

**Comment by kjdchapman** [comment]
Ah, OK. I am happy to avoid a checklist like that. Here's some example text!
_____

### Context

_Why are you making this change? What might surprise someone about it?_

### Guidance to review

_How could someone else check this work? Which parts do you want more feedback on?_

____

Feel free to incorporate/ignore this and merge! :rocket:

**Comment by duncanjbrown** [comment]
Thank you — added and merged

**Pull request merged**
