### PR TITLE
Add ProviderInterface::HeaderComponent & spec

### PR DESCRIPTION
**Pull request by willmcb**
## Context

New header component for provider interface

## Changes proposed in this pull request

**Before**
Screenshot 2020-05-27 at 11 39 45

**After**
Screenshot 2020-05-27 at 16 44 48

## Guidance to review

- does it look okay throughout the app?

## Link to Trello card

https://trello.com/c/st1Mq1h6/2005-build-implement-the-new-header-for-manage-applications

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by adamsilver** [comment]
I feel like there should be on component called Header which can be called with different params provider compared to candidate or support.

This looks like the bulk of the header HTML has been duplicated/hard coded. 

What's the thinking on this?

**Comment by willmcb** [comment]
Thinking was that really it is a simple way to do it, given that this might change in the near future it is easy to just replace one with the other rather than baking conditional logic into the component. 

Currently there is already conditional logic in the `_header.erb` view that can be used to render different components so I thought this was the straightest way of going about this change. 

The new header is completely encapsulated in one place under a given namespace - if we need to use it more widely we can just remove it from that name space add it to the global name space and there is no real need to change the code much (other than some module names). 

If we have to add conditional logic to the component and then we decide to go with the newer version we would have to delete the redundant conditional logic in any case.

**Comment by adamsilver** [comment]
No worries @willmcb @duncanjbrown – all good.

I know it's slightly different but that's fine.

The prototype doesn‘t have the email so let's leave it as it doesn't navigate anywhere.

**Comment by duncanjbrown** [comment]
@adamsilver just confirming you're happy with the way this looks?

**Comment by adamsilver** [comment]
Approved

**Pull request merged**
