### PR TITLE
Fix font size and spacing on applications appearing in provider application index

### PR DESCRIPTION
**Pull request by willmcb**
## Context

Fixes font sizes and spacing of note messages on application cards on the provider interface application index view.

## Changes proposed in this pull request

**Before:**
Screenshot 2020-06-01 at 16 15 12

**After:**
Screenshot 2020-06-01 at 16 14 23

## Guidance to review

- Does it look like it matches the design to you?

## Link to Trello card

https://trello.com/c/d1WgjClI/2218-wrong-font-size-and-spacing-on-applications-appearing-in-the-list

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by adamsilver** [comment]
Font size looks good

Spacing isn’t quite right. The long note text should wrap onto multiple lines instead of pushing the left hand content down.

**Comment by willmcb** [comment]
Screenshot 2020-06-02 at 16 06 47

**Comment by adamsilver** [comment]
Hey @willmcb – I made a video of the remaining issues.

https://www.loom.com/share/00b960c278174d5083160503000aa891

**Comment by willmcb** [comment]
@adamsilver the bug also appears on the prototype - it is due to having three particularly long words and having `word-break: normal` set there is nowhere for things to break other than in whitespaces so it causes this issue. 

You can set `word-break: break-all` and this will break mid word but I'm not sure that is preferable:

Screenshot 2020-06-05 at 14 56 53

**Comment by willmcb** [comment]
Have rolled back to add a `<span>` for the bullet point and added `aria-hidden="true"` and so that it is ignored by screen readers - result being:

Screenshot 2020-06-08 at 14 30 14

**Pull request merged**
