### PR TITLE
Only display synced providers when editing provider permissions in support

### PR DESCRIPTION
**Pull request by tvararu**
## Context

This should dramatically reduce the size of the page (currently 3.7MB) and the time it takes to render (42 seconds).

Also update the tag for the legend to be a h2 instead of a h1.

## Changes proposed in this pull request

Only query for synced providers for the `_provider_options` template.

## Guidance to review

Do we need to display unsynced providers in this view?

## Link to Trello card

https://trello.com/c/chVDLTwn/1928-build-speed-up-the-add-a-provider-user-page-in-support

## Things to check

- [x] This code doesn't rely on migrations in the same Pull Request
- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] API release notes have been updated if necessary
- [x] New environment variables have been [added to the Azure config](https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training#azure-hosting-devops-pipeline)

### CODE REVIEW

**Comment by tvararu** [comment]
Seems to work on the review app

**Comment by davidgisbey** [comment]
If the users from accredited bodies  (i.e. a university) _should_ be added as provider_users for the providers whose courses they accredit, then I don't see why they are needed.

**Comment by duncanjbrown** [comment]
https://trello.com/c/chVDLTwn/1928-build-speed-up-the-add-a-provider-user-page-in-support

**Comment by tvararu** [comment]
Added tests too!

**Comment by tvararu** [comment]
On QA: 3.7MB down to 52KB, 42 seconds down to 591ms. 🎉

**Pull request merged**
