### PR TITLE
Refactor to re-use presenters between candidate/provider interfaces

### PR DESCRIPTION
**Pull request by tijmenb**
### Context

Why are you making this change? What might surprise someone about it?

### Changes proposed in this pull request

If there are UI changes, please include Before and After screenshots.

### Guidance to review

How could someone else check this work? Which parts do you want more feedback on?

### Link to Trello card

[123 - Example Trello card](http://trello.com/123-example-card)

### CODE REVIEW

**Comment by duncanjbrown** [comment]
Very happy to see this done!

The difference between this code and the model & service code with which it now shares the top-level namespace is that this is only associated with provider and candidate UI. Would there be any value in creating a new namespace to give it (and its future siblings) somewhere to live? `SharedUIComponents` or sth.

**Comment by tvararu** [comment]
👍 

@duncanjbrown not sure the namespace is needed; at least to me, it's intuitive that the components are meant to be shared if they are in the global namespace. 🤔

**Comment by duncanjbrown** [comment]
> 👍
> 
> @duncanjbrown not sure the namespace is needed; at least to me, it's intuitive that the components are meant to be shared if they are in the global namespace. 🤔

Exactly — they are to be shared. The idea of a namespace is that not everything shares them. Possibly `SharedUIComponents` is the wrong sort of idea.

**Comment by tijmenb** [comment]
Closing this until we have a few more forms, I don't think we've found the correct abstraction yet!

**Pull request closed without merging**
